CREATE TABLE IF NOT EXISTS faculty_members ("Sno." TEXT, "Machine learning faluty" TEXT, "Email" TEXT);
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('1', 'Dr.shalini batra', 'sbatra@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('2', 'Dr. Rinkle Rani', 'raggarwal@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('3', 'Dr. Seema Bawa', 'seema@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('4', 'Dr. Sushma Jain', 'sjain@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('5', 'Dr. Ravinder Kumar', 'ravinder@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('6', 'Dr. Karun Verma', 'karun.verma@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('7', 'Dr. Prashant S Rana', 'prashant.singh@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('8', 'Dr. Rajesh Mehta', 'shailendra@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('9', 'Dr. Rajendra Kumar Roul', 'raj.roul@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('10', 'Dr. Husanbir Singh Pannu', 'hspannu@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('11', 'Dr. Karamjeet Singh', 'karamjeet.singh@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('12', 'Dr. Jasmeet Singh', 'jasmeet.singh@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('13', 'Dr. Jatin Bedi', 'jatin.bedi@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('14', 'Dr. Shivani Sharma', 'shivani.sharma@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('15', 'Dr. Mansi Sharma', 'shivani.sharma@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('16', 'Dr. Simranjit Kaur', 'simranjit.kaur@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('17', 'Dr. Ravneet Kaur', 'ravneet.kaur1@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('18', 'Dr. Amit Kumar Trivedi', 'amitkumar.trivedi@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('19', 'Dr. Kuntal Chowdhury', 'kuntal.chowdhury@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('20', 'Dr. Seema Wazarkar', 'seema.wazarkar@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('21', 'Dr. Jyoti', 'Jyoti.maggu@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('22', 'Dr. Javed Imran', 'javed.imran@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('23', 'Dr. Saif Nalband', 'saif.nalband@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('24', 'Dr. Aditi Sharma', 'aditi.sharma@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('25', 'Dr. Rahul Nijhawan', 'rahul.nijhawan@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('26', 'Dr. Jinee Goyal', 'jinee.goyal@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('27', 'Dr. Arun Singh Pundir', 'arun.pundir@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('28', 'Dr. Mandeep Kaur', 'mandeep.bajwa@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('29', 'Dr. Nitin Arora', 'nitin.arora@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('30', 'Dr. Anjula Mehto', 'anjula.mehto@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('31', 'Dr. Ashish Bajaj', 'ashish.bajaj@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('32', 'Dr. Himika Sharma', 'himika.sharma@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('33', 'Mrs. Ashima Khosla', 'ashima.khosla@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('34', 'Dr. Abhishek Kesarwani', 'abhishek.kesarwani@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('35', 'Dr. Harkiran Kaur', 'harkiran.kaur@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('36', 'Dr. Harpreet Singh', 'harpreet.s@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('37', 'Ms. Sujata Rani', 'sujata.singla@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('38', 'Dr. Sanjeev Rao', 'sanjeev.rao@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('39', 'Dr. Amrita Kaur', 'amrita@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('40', 'Dr. Shivani Goswami', 'shivani.goswami@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('41', 'Dr Vijay Kumari', 'vijay.kumari@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('42', 'Dr. Abdul Kadir', 'abdul.kadir@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('43', 'Ms. Stuti Chug', 'stuti.chug@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('44', 'Dr. Jasleen Kaur', 'bedijasleen1313@gmail.com');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('45', 'Dr. Satbir Singh', 'satbir.singh@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('46', 'Dr. Kashish Goyal', 'kashishgoyal31@gmail.com');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('47', 'Dr. Shabnam Bawa', 'subhsubhbawa@gmail.com');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('48', 'Dr. Tanya Garg', 'tanya.garg@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('49', 'Dr. Sanju Kumari Singh', 'sanju.singh@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('50', 'Ms Gursimran Kaur', 'gursimran.kaur@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('51', 'Shruti Arora', 'shruti.arora@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('52', 'Ashiq Nazir Bhat', 'ashiqnazirbhat@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('53', 'Raghuveer Singh Dhaka', 'rdhaka_phd21@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('54', 'Bharti', 'bharti1@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('55', 'Navpreet', 'navpreet1@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('56', 'Kudratdeep Aulakh', 'kudratdeep.aulakh@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('57', 'Amardeep Singh', 'amardeep.singh@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('58', 'Priya Kansal', 'nope ');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('59', 'kudratdeep.aulakh', 'ikaur_phd23@thapar.edu');
INSERT INTO faculty_members ("Sno.", "Machine learning faluty", "Email") VALUES ('60', 'Rajesh Kumar Chaudhary', NULL);
